### ISSUE TITLE
Serialized object cannot be cast to type

### ISSUE THREAD

**Issue by ghost** [dkunzler/esperandro#23]
java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to com.example.data.Item
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2215)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2265)

When reading an `ArrayList<Item>` from SharedPreferences, objects stored in the ArrayList cannot be cast to their initial type (are not de-serialized). 

Item class implements Serializable, Esperandro is using its default serializer. 

```
public class Item implements Serializable {
    String title;
    String desc;
}
```

```
@SharedPreferences
public interface LocalStorageInterface {
    ArrayList<Item> localItems();
    void localItems(ArrayList<Item> items);
}
```

**Comment by asadkt** [comment]
serialization of custom serialized POJO into shared preference returns null upon trtrieval

**Comment by dkunzler** [comment]
Hi,

can you please elaborate your problem? Perhaps by showing the code you are using.
I cannot understand your problem at this time.

**Comment by asadkt** [comment]
I got following exception while running "Test Esperandro shared preferences"

E/AndroidRuntime: FATAL EXCEPTION: main
                                Process: com.xyz.android.debug, PID: 28996
                                java.lang.NullPointerException: Attempt to invoke virtual method 'int com.xyz.android.api.model.TestObj.getMember1()' on a null object reference


**Test Esperandro shared preferences**

`		//
		SharedPref sharedPref = SharedPrefHelper.getInstance(getContext());
		TestObj testObj= new TestObj();
		testObj.setMember1(23);
		sharedPref.setTestObj(testObj);
		testObj =sharedPref.getTestObj();
		Log.d(TAG, "TestObj shared preference value: " + testObj.getMember1());`

**TestObj.java**

`import java.io.Serializable;

public class TestObj implements Serializable {

    private int member1;

    public int getMember1() {
        return member1;
    }

    public void setMember1(int member1) {
        this.member1 = member1;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        TestObj testObj = (TestObj) o;
        return member1 == testObj.member1;
    }

    @Override
    public int hashCode() {
        return member1;
    }
}`

**SharedPref.java**

`import com.kindertales.android.api.model.TestObj;
import de.devland.esperandro.SharedPreferenceMode;
import de.devland.esperandro.annotations.SharedPreferences;

@SharedPreferences(name = "defaults", mode = SharedPreferenceMode.PRIVATE)
public interface SharedPref {

	boolean setTestObj(TestObj testObj);
	TestObj getTestObj();
}`

**SharedPrefHelper.java**

`import android.content.Context;
import de.devland.esperandro.Esperandro;
import de.devland.esperandro.serialization.GsonSerializer;

public class SharedPrefHelper {

	private Context context;
	private static SharedPref sharedPref;

	private SharedPrefHelper() {
	}
	
	public static SharedPref getInstance(Context context) {
		context = context;
		if (sharedPref == null) {
			sharedPref = Esperandro.getPreferences(SharedPref.class, context);
			Esperandro.setSerializer(new GsonSerializer());
		}
		return sharedPref;
	}
}`

**Comment by dkunzler** [comment]
OK, your interface definition is wrong. esperandro doesn't use set and get keywords as semantic. Just use the name of the preference you want to store. In your case:

```
import com.xyz.android.api.model.TestObj;
import de.devland.esperandro.SharedPreferenceMode;
import de.devland.esperandro.annotations.SharedPreferences;

@SharedPreferences(name = "defaults", mode = SharedPreferenceMode.PRIVATE)
public interface SharedPref {

    boolean testObj(TestObj testObj);
    TestObj testObj();
}
```

In your example you would store a preference named `setTestObj` and try to read a preference named `getTestObj`

I hope this helps.

**Comment by asadkt** [comment]
David, it works now.

**Comment by asadkt** [comment]
Just recalled that get/set prefix works with primitive types

**Comment by dkunzler** [comment]
No it doesn't. At least not in esperandro. Not sure what you are doing but I definately not implemented set/get prefixes.
