### ISSUE TITLE
if the data is too lager(22.17K) ,and load will be change so slowly

### ISSUE THREAD

**Issue by 1252768410** [dkunzler/esperandro#32]
Now ,I use this lib to store a List data like this

ArrayList<District>districts = filterConfigEntity.getDistricts();
 getSharePrefence(DistrictsListSharePreference.class).containerValueAsync(districts);

but when i get it ,load data will beslowly, many times  it's need three seconds or more , can you give me some advice,thanks

**Comment by dkunzler** [comment]
Hi @1252768410 
I guess that's just too much data. SharedPreferences are specifically designed to handle "relatively small collections of key-values". (http://developer.android.com/training/basics/data-storage/shared-preferences.html)
For such amount of data like large Lists a real database is more suited. Even if esperandro allows you to store structured data into the SharedPreferences it doesn't make them a database.

Nevertheless another approach could be to use another Serializer. I don't know how well gson handles large lists of data. You could go and try jackson or even use a completely different approach (Serializer interface is there) on your own.

@stonecs any more thoughts on this?

**Comment by stonecs** [comment]
Hi,

in general, I also think this is the wrong use case for Preferences.

Esperandro only wraps around the actual SharedPreference logic and should not add significant overhead. The only thing, as @dkunzler already mentioned, that could lead to an overhead to simply storing a string of this size is the (de)serialization.

~stonecs

**Comment by dkunzler** [comment]
If you want to know the performance impact of serialization alone you could do something like this:

```
public class TimeMeasuringGsonSerializer extends GsonSerializer {

	@Override
    public String serialize(Object object) {
		Log.d("Esperandro", "Start serializing at: " + System.nanoTime());
		String result = super.serialize(object);
		Log.d("Esperandro", "Finished serializing at: " + System.nanoTime());
		return result;
	}

	@Override
    public <T> T deserialize(String serializedObject, Class<T> clazz) {
		Log.d("Esperandro", "Start deserializing at: " + System.nanoTime());
		T result = super.deserialize(serializedObject, clazz);
		Log.d("Esperandro", "Finished deserializing at: " + System.nanoTime());
		return result;
	}
}
```

and somewhere in your initialization code:
```
Esperandro.setSerializer(new TimeMeasuringGsonSerializer());
```

(if you are using GsonSerializer at the moment. adapt if you use another)
You should then see the start and end time of serialization and deserialization and could determine if this has something to do with your perfomance issue. If not SharedPreferences are not suitable for this use-case and you have to use the database.

Disclaimer: just hacked this together in notepad. No guarantee it will compile without editing.

**Comment by 1252768410** [comment]
thanks your response ,Maybe I should be use database,. or if i have time I will be use GSON parser, Now I used FastJson   https://github.com/alibaba/fastjson.
