### ISSUE TITLE
sometimes, when I need serializ object , but I don't want to serialzed object's some field

### ISSUE THREAD

**Issue by 1252768410** [dkunzler/esperandro#33]
Now do you have any idea ? thanks

**Comment by dkunzler** [comment]
That depends highliy on the Serializer.
Gson for example uses two different approaches: You can either mark a field ``transient`` or use ``@Expose`` and set ``GsonBuilder().excludeFieldsWithoutExposeAnnotation()`` when building the GSON Object. (The esperandro GSON Serializer can be instantiated with such a gson instance)
https://sites.google.com/site/gson/gson-user-guide#TOC-Excluding-Fields-From-Serialization-and-Deserialization

For other serialization techniques there could be other solutions.

**Comment by 1252768410** [comment]
Thanks for your response! ^_^
