### ISSUE TITLE
Async setters

### ISSUE THREAD

**Issue by MFlisar** [dkunzler/esperandro#39]
Whenever changing a value, this may be blocking the UI if it happens on the UI thread... I think, most of the time, async setters would be fine as well (and maybe better?).

So something that allows me to decide if `commit()` or `apply()` should be used would be really nice... Maybe a setter function with a boolean parameter additional to the default? This would not break any existing API.

Instead of generating following:

	@Override
	public boolean lastSelectedColor(int lastSelectedColor) {
		cache.put("lastSelectedColor", lastSelectedColor);
		return preferences.edit().putInt("lastSelectedColor", lastSelectedColor).commit();
	}
	
You could generate something like following:	
	
	@Override
	public Boolean lastSelectedColor(int lastSelectedColor) {
		return lastSelectedColor(lastSelectedColor, true);
	}
	
	@Override
	public Boolean lastSelectedColor(int lastSelectedColor, boolean commitImmediately) {
		cache.put("lastSelectedColor", lastSelectedColor);
		Editor editor = preferences.edit().putInt("lastSelectedColor", lastSelectedColor);
		if (commitImmediately)
			return editor.commit();
		editor.apply();
		return null; // we don't know the success state...
	}

**Comment by dkunzler** [comment]
If I'm correct (this part of the code is a bit older) I do always apply instead of commit if you define your interface like
``
void lastSelectedColor(int lastSelectedColor)
``
and I use commit if you define 
``
boolean lastSelectedColor(int lastSelectedColor)
``

If that doesn't work correctly for you, please reach back to me here.

**Comment by MFlisar** [comment]
That's correct, thanks. I anyways never check the result and therefore can change my preference interface to use the void version
