### ISSUE TITLE
Cache problem with null values

### ISSUE THREAD

**Issue by MFlisar** [dkunzler/esperandro#42]
With cache enabled, generated code may look like following:

	 @Override
	  public DataManager.ExistingDataSources existingDataSources() {
		DataManager.ExistingDataSources __result = (DataManager.ExistingDataSources) cache.get("existingDataSources");
		if (__result == null) {
		  Serializer __serializer = Esperandro.getSerializer();
		  __result = __serializer.deserialize(preferences.getString("existingDataSources", null), com.michaelflisar.gallery.data.DataManager.ExistingDataSources.class);
		  cache.put("existingDataSources", __result);;
		}
		return __result;
	  }

This is a custom serialisable field of mine, the problem is, if it is not initialised or is null, the `cache.put("existingDataSources", __result);;` will throw a `java.lang.NullPointerException: key == null || value == null` exception.

Can this be changed to allow null values? Any reasons, why this is not possible yet?

Btw, the code generator is generating double ; as you can see in my code example... Not a big deal though, so I'm just mentioning it here...

PS: currently I'm using following version:

    compile 'de.devland.esperandro:esperandro-api:2.3.1'
    apt 'de.devland.esperandro:esperandro:2.3.1'

**Comment by dkunzler** [comment]
I will release a fix tomorrow.

**Comment by MFlisar** [comment]
Thanks

**Comment by dkunzler** [comment]
2.4.0 should be available in maven central in a few hours.
Cached and GenerateStringResource Annotations moved to experimental package
