### ISSUE TITLE
Suggestion - use string definitons with generated preference class

### ISSUE THREAD

**Issue by MFlisar** [dkunzler/esperandro#45]
It's now possible to generate string resources for each preference. Can you extend the generated class with following function:

    // prefID... one of the generated string resources via @GenerateStringResources
    public <T> T getValue(Context context, int prefId);
    public <T> boolean setValue(Context context, int prefId, T value);

Those functions should use the cache if enabled as well. My settings view library is finished now and with this extension I could use your preferences perfectly with it.

Implementation could look like following:

    // 1) Map all existing ids to a class
	private HashMap<Integer, Class> mPreferenceMap = new HashMap();
	mPreferenceMap.put(R.string.<PREFERENCE>, Boolean.class);
	// ...
	
	// 2) create getter
	public <T> T getValue(Context context, int id) {
        Class clazz = mPreferenceMap.get(id);
        if (clazz == null) {
            throw new RuntimeException("Please only use string resource ids generated via @GenerateStringResources");
        }
        String stringId = context.getString(id);
        Object __result = cache.get(stringId);
        if (__result == null) {
            if (clazz.equals(Boolean.class)) {
                __result = preferences.getBoolean(stringId, false);
            } else {
                // handle other existing preference classes as wll
            }
            if (__result != null) {
                cache.put(stringId, __result);
            }
        }
        return __result;
    }
	
	// 3) and setter
	public <T> boolean setValue(Context context, int id, T value) {
        Class clazz = mPreferenceMap.get(id);
        if (clazz == null) {
            throw new RuntimeException("Please only use string resource ids generated via @GenerateStringResources");
        }
        String stringId = context.getString(id);
        cache.put(stringId, value);
        if (clazz.equals(Boolean.class)) {
            return preferences.edit().putBoolean(stringId, value).commit();
        } else {
                // handle other existing preference classes as wll
            }
    }

**Comment by dkunzler** [comment]
Hi,

seems nice, I will add this feature for you soon.

**Comment by dkunzler** [comment]
Sorry for the huge delay. It is now added as methods in the interface UnsafeActions.
You can have a look if this suits your needs (if you still want it).
Version 2.5.2, can take a few hours until you see it on your mirror.

**Comment by MFlisar** [comment]
No need to apologise, I appreciate that you added this for me.

Looks good so far. This saves me a few lines of code in the future:

    // new code
    withGlobal(R.string.darkTheme);

    // old code
	// withGlobal(
	//         () -> MainApp.getPrefs().darkTheme(),
	//         value -> MainApp.getPrefs().darkTheme(value)
	// );
