### ISSUE TITLE
Compiler warning if setting default values to default

### ISSUE THREAD

**Issue by MFlisar** [dkunzler/esperandro#48]
If I set a default value that is the same as the annotations default value I get a compiler warning from here:

https://github.com/dkunzler/esperandro/blob/42144cb0a4575383eced3d3c556dab9ce5abf325/processor/src/main/java/de/devland/esperandro/processor/Warner.java#L41

Why is this necessary?

    // @Default(ofBoolean = false) // <= uncommenting this will produce the warning
    boolean test();
    boolean test(boolean test);

I always define the default values as I want to see it in my code and to make sure that it is the value I expect it to be and want it to be

**Comment by dkunzler** [comment]
You are right, this is a regression and was originally correct. It should only warn when you define a non-default default value of another type. Will get fixed very soon.

**Comment by dkunzler** [comment]
@MFlisar fixed in 2.6.0

**Comment by MFlisar** [comment]
Great, thank you
