### ISSUE TITLE
Java version - support java 8

### ISSUE THREAD

**Issue by MFlisar** [dkunzler/esperandro#52]
In my gradle console log I always see following:

```
warning: No SupportedSourceVersion annotation found on de.devland.esperandro.processor.EsperandroAnnotationProcessor, returning RELEASE_6.
warning: Supported source version 'RELEASE_6' from annotation processor 'de.devland.esperandro.processor.EsperandroAnnotationProcessor' less than -source '1.8'
```

I'm using java 8 (for lambdas and other new java features) in all my projects, would it be possible to get rid of this warning? Could you add java 8 support to this library?

It's no big deal as it's a warning only and it does not have any effect, still...

**Comment by dkunzler** [comment]
Unfortunately it seems a bit complicated. I'm unsure about the impact if I set RELEASE_8 but somebody uses it without Java 8 language features in his build. I will look into it however.

**Comment by dkunzler** [comment]
I just solved it potentially. If you have the time to try the new 2.7.0 let me know if the warning is gone for you.

**Comment by MFlisar** [comment]
Looks great, no warning anymore and generated class is the same and working. Thanks
