### ISSUE TITLE
Incremental annotation processor

### ISSUE THREAD

**Issue by naixx** [dkunzler/esperandro#53]
Will it be possible to support incremental APT?
https://docs.gradle.org/4.7/userguide/java_plugin.html#sec:incremental_annotation_processing

**Comment by dkunzler** [comment]
Hi,

I will have a deeper look into it. But I think it isn't possible in the current design because I'm also generating the String resources. I guess I have to externalize the resource generation into an own Processor. (which in turn won't be incremental)

**Comment by wbervoets** [comment]
any update on this ticket?

**Comment by dkunzler** [comment]
Unfortunately not. I currently don't have time for side projects. Perhaps in the next month again.

**Comment by dkunzler** [comment]
I'm uploading 3.0.0 right now.
I split the functionality into 3 seperate processors. 2 of them are incremental, the resource generation is not and at the moment cannot be incremental.
Please read the changelog since artifacts and some other things changed. (and the readme is not yet updated)
