### ISSUE TITLE
AndroidX - import problem

### ISSUE THREAD

**Issue by MFlisar** [dkunzler/esperandro#55]
After migrating to androidx I have following problem:

The generated preference class is importing `androidx.core.util.LruCache` instead of `androidx.collection.LruCache`. Problem happens with following setup: `@Cached(cacheOnPut = true, support = true)`, only if`support = true` is used of course.

**Comment by MFlisar** [comment]
No need to hurry, enjoy your vacation. Actually there is no need to use the support version anyways...

Probably the androidx namespace comes from the automatic refactoring android studio can do for libraries working with appcompat where the namespace comes from... ( the `enableJetifier` flag)

**Comment by dkunzler** [comment]
I'm uploading 3.0.0 right now where you can choose which LruCache implementation is used. This should hopefully fix this error.
Please read the changelog since artifacts and some other things changed. (and the readme is not yet updated)
