### ISSUE TITLE
warning: No SupportedSourceVersion annotation found on de.devland.esperandro.processor.EsperandroAnnotationProcessor, returning RELEASE_6.

### ISSUE THREAD

**Issue by anthony3444** [dkunzler/esperandro#56]
Hi there!

A question about this warning: 
warning: No SupportedSourceVersion annotation found on de.devland.esperandro.processor.EsperandroAnnotationProcessor, returning RELEASE_6.

How can I fix it please?

Thank you very much!

**Comment by dkunzler** [comment]
Hi, this should be fixed since 2.7.0 which came out in february 2018.
Do you still have this issue with a current verison?

**Comment by dkunzler** [comment]
Should be fixed in 3.0.0
