### ISSUE TITLE
Poll: Change method names to Java Bean Accessor Syntax

### ISSUE THREAD

**Issue by dkunzler** [dkunzler/esperandro#63]
After seeing the discussion in #62 I think about adding the required naming scheme as additional possibility or changing the syntax completely in a new release.

So this poll is about:
a) add the possibility to use set<propertyName> and get<propertyName> additionally to the current <propertyName> method names where only the parameter determine the set/get operation.
b) completely remove support for access via <propertyName> only method names and completely change it to set<propertyName>/get<propertyName>

Pros/Cons for the set/get naming scheme:
- (+) compliant to Java Bean Naming Convention and therefore better compatibility with potential other technologies like Kotlin
- (+) more visible distinction between getter and setter
- (-/+) getters with runtime defaults do not necessarily need a prefix and therefore a different name (`getProperty(String default)` would work whereas now it is `property$Default(String default)`)
- (-) extreme breaking API change
- (-) understanding what the actual name of the preference will be is quite harder. (take the case into account: setProperty would still save into `property` not `Property`)

Apologize for tagging you people, but you are the only ones I know that use the library, so to get feedback I specifically ask: @danielneu @mflisar @dmo60 @rguthor2 @anthony3444 @naixx @asadkt
Hopefully you are not mad about this :D 

Thanks in Advance for feedback

**Comment by MFlisar** [comment]
Before I answer, did you ever think about moving this library on to kotlin? This may open up new possibilities and even some things can be done without annotation processing...

**Comment by dkunzler** [comment]
No, apart from the basic Syntax I'm not that familiar with advanced kotlin features.
Do you have more insight on what of this lib can be done in kotlin without annotation processing?

**Comment by MFlisar** [comment]
You can check out this library: https://github.com/chibatching/Kotpref namely it's mostly kotlin delegates you can use to set/get values. For many use cases the linked library may be already a full kotlin alternative to your library - your library has some special features I use that make me still prefer your library.

If you move your library to kotlin and use fields for preference values, the getter/setter problem in java will be solved automatically as well as a simple side effect.

**Comment by dmo60** [comment]
> (-) extreme breaking API change

Supporting both the old and the getter/setter syntax would probably be the less intrusive change. But it comes with a slight cost of decreased ease of use (one more feature to explain, one more decision to take).

> (-) understanding what the actual name of the preference will be is quite harder. (take the case into account: setProperty would still save into property not Property)

It's probably a bad idea to guess and hardcode the name of the property anyways. For the use-case where the actual key name is required, you could advertise the key-gen processor.

**Comment by dkunzler** [comment]
Thanks for all your feedback.
I will make a new major version with changed naming in the future. Stay tuned.
This also affect #62
