### ISSUE TITLE
Memory leak in ProcessingMessager

### ISSUE THREAD

**Issue by Tapchicoma** [dkunzler/esperandro#65]
Recently we start hitting quite constantly "GC overhead limit exceeded" error on building our application.

We managed to take heap dump of kotlin deamon process when this happens and, after analyzing it, we saw that `ProcessingMessager` consumes a lot of kotlin daemon heap memory.

Seems main issue that `ProcessingMessager` itself is singleton and holds a reference to `JavacProcessingEnvironment` here https://github.com/dkunzler/esperandro/blob/d88d8e7cee508a24af921190802412167dc2175e/base/src/main/java/de/devland/esperandro/base/processing/ProcessingMessager.java#L37. This prevents GC to remove a lot of portions of heap.

**Comment by dkunzler** [comment]
Hi, thank you for your analysis. Can you provide me with the heap dump you took? How large is it?

**Comment by Tapchicoma** [comment]
It is 8Gb in size. Will think how could it be provided.

**Comment by dkunzler** [comment]
ok, that's more than I expected.
Perhaps we could use https://www.justbeamit.com/ for a P2P transfer.

**Comment by Tapchicoma** [comment]
@dkunzler contact me when your are ready to receive heap dump

**Comment by dkunzler** [comment]
@Tapchicoma I'm available now. You can send me the link via mail to not expose it to other people.
dk@devland.de

**Comment by dkunzler** [comment]
Hi, I coult analyze the heap you gave me, and in fact I can see that the processingEnv should not be retained as a static field here. 
I will start working on that asap.

**Comment by dkunzler** [comment]
Can you give a feedback if 3.0.2 works for you if you tried it? Thanks.
@Tapchicoma

**Comment by Tapchicoma** [comment]
Sorry, we removed Esperandro from our repository and I don't have time to test it. If it still happens, somebody will open an issue again :slightly_smiling_face:
