### ISSUE TITLE
Proguard configuration (revisited)

### ISSUE THREAD

**Issue by cstaszak-logicboostlabs** [dkunzler/esperandro#68]
Although the notes in issue #24 were helpful, they did were not working for me (to be fair, that was six years ago). Using those rules, proguard still ends up name mangling the annotated class and not including the generated $$Impl class, which is effectively fatal for any proguard processed application.

I'm not a proguard expert, but was able to come up with a workable solution in my `proguard-rules.pro`:

```
# Esperandro
# Kept intact from issue #24
-keepattributes *Annotation*, EnclosingMethod, Signature, InnerClasses
-keepnames class de.devland.** { *; }

# Added to prevent any @SharedPreferences annotated class from being modified
-keep @de.devland.esperandro.annotations.SharedPreferences class *

# Ensure the generated class is not optimized away, since it is only referenced through reflection
# The matching pattern from issue #24 was not working for me, note the subtle difference
-keep public class **.*$$Impl { *; }
```

It would be extremely useful to have this (or perhaps a more optimal solution) formally documented and/or simply bundled into a future library update. In the meantime, this may be helpful here for others encountering the same issue.

**Comment by dkunzler** [comment]
Hi, thanks for your feedback. I will add that to the documentation. 
And if I ever switch to gradle I will put it directly into the lib.

**Comment by dkunzler** [comment]
I added a combination of your version and the one from #24 in the wiki. (that I will have to update a lot more...)
https://github.com/dkunzler/esperandro/wiki/ProGuard
Thanks a lot
