### ISSUE TITLE
Deprecation warnings after migration to CompileSDK 29

### ISSUE THREAD

**Issue by rguthor2** [dkunzler/esperandro#77]
After migration to the compilesdk 29 lots of deprecation warnings regarding the use of android.preference.PreferenceManager are generated. The reason seems to be in the generated files of the annotation processor. 
Can this be configured to use androidx.preference.PreferenceManager or does this need a new esperandro version?

**Comment by dkunzler** [comment]
I will have a look at it and provide either an alternative implementation or a configuration to use the androidx namespace.
Currently it cannot be configured so I need to make a fix in esperandro.

**Comment by rguthor2** [comment]
Hallo David,

ich finde das toll, dass du dich immer noch darum kümmerst. Hoffe mal dass ich nicht der einzige User bin J

 

Viele Grüße

Rainer

 

Von: David Kunzler [mailto:notifications@github.com] 
Gesendet: Donnerstag, 22. Oktober 2020 00:13
An: dkunzler/esperandro
Cc: Rainer Guthor; Author
Betreff: Re: [dkunzler/esperandro] Deprecation warnings after migration to CompileSDK 29 (#77)

 

I will have a look at it and provide either an alternative implementation or a configuration to use the androidx namespace.
Currently it cannot be configured so I need to make a fix in esperandro.

**Comment by dkunzler** [comment]
Hi Rainer, ich benutze es nach wie vor selbst, sowohl private als auch in der Firma. Meine Kollegen sind auch noch schwer begeistert ;)
Soviel ich weiß gibt es auch noch eine handvoll Leute, die ich nicht kenne, die es nutzen.

I just released 4.0.1 that should fix this issue by not using PreferenceManager at all anymore.

**Comment by rguthor2** [comment]
Hallo David,

habe es eben gesehen und gleich ausprobiert. Funktioniert wie angekündigt. 

 

Also noch mal vielen Dank, dass du so schnell reagiert hast.

 

Vielleicht können wir uns ja mal treffen wenn Corona vorbei ist und bevor die nächste Pandemie gehyped wird.

 

 

Viele Grüße

Rainer

 

 

Von: David Kunzler [mailto:notifications@github.com] 
Gesendet: Sonntag, 25. Oktober 2020 23:13
An: dkunzler/esperandro
Cc: Rainer Guthor; Author
Betreff: Re: [dkunzler/esperandro] Deprecation warnings after migration to CompileSDK 29 (#77)

 

Hi Rainer, ich benutze es nach wie vor selbst, sowohl private als auch in der Firma. Meine Kollegen sind auch noch schwer begeistert ;)
Soviel ich weiß gibt es auch noch eine handvoll Leute, die ich nicht kenne, die es nutzen.

I just released 4.0.1 that should fix this issue by not using PreferenceManager at all anymore.
